[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { 
    DATABASE_PATH = "/app/DataBase.db",
    PERSISTENT_STORAGE = "true"
}
